version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: threatintel
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/threatintel
      PORT: 3000
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    restart: always
    environment:
      VITE_API_URL: http://localhost:3000
    # volumes:
    #   - ./frontend:/app

volumes:
  db_data: 